// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZML0lU_3WoLqjRnceutWeOVIHllOFok',
    appId: '1:652445272044:android:bc472d5d6bcd0d2f1f62c9',
    messagingSenderId: '652445272044',
    projectId: 'sept-app',
    storageBucket: 'sept-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5wcgf3lZTzGSec0Mhb7Q5cMCaooNZWFs',
    appId: '1:448101294701:ios:29525995511dd1ac911564',
    messagingSenderId: '448101294701',
    projectId: 'sext-app',
    storageBucket: 'sext-app.appspot.com',
    iosBundleId: 'com.example.ambientes2',
  );

}