// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4QtPAOeUfF309HaLRoGqw_7YL0vvZ9o',
    appId: '1:448101294701:web:653cc36638506c27911564',
    messagingSenderId: '448101294701',
    projectId: 'sext-app',
    authDomain: 'sext-app.firebaseapp.com',
    storageBucket: 'sext-app.appspot.com',
    measurementId: 'G-SJDSCDNPQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxXoxhF_ANwuop9hYnb3LiLispJdyAyc',
    appId: '1:448101294701:android:2812303e789c27b9911564',
    messagingSenderId: '448101294701',
    projectId: 'sext-app',
    storageBucket: 'sext-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5wcgf3lZTzGSec0Mhb7Q5cMCaooNZWFs',
    appId: '1:448101294701:ios:29525995511dd1ac911564',
    messagingSenderId: '448101294701',
    projectId: 'sext-app',
    storageBucket: 'sext-app.appspot.com',
    iosBundleId: 'com.example.ambientes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5wcgf3lZTzGSec0Mhb7Q5cMCaooNZWFs',
    appId: '1:448101294701:ios:29525995511dd1ac911564',
    messagingSenderId: '448101294701',
    projectId: 'sext-app',
    storageBucket: 'sext-app.appspot.com',
    iosBundleId: 'com.example.ambientes2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw4QtPAOeUfF309HaLRoGqw_7YL0vvZ9o',
    appId: '1:448101294701:web:bcd0f8cf9e66b218911564',
    messagingSenderId: '448101294701',
    projectId: 'sext-app',
    authDomain: 'sext-app.firebaseapp.com',
    storageBucket: 'sext-app.appspot.com',
    measurementId: 'G-NBYJHBRLEP',
  );

}